### ISSUE TITLE
Ununderstandable results when simulating a simple model

### ISSUE THREAD

**Issue by fifarraj** [chenyutao36/MATMPC#2]
Hello,

Thank you for the very nice work. This is a great toolbox with a lot of potential. 

I have been playing around with the toolbox and while your examples work and some of my models also worked well, I noticed some issues which I could not explain. Basically, in some scenarios, the system does not manage to achieve the target value of the DoF even if it could. It gets close but not quite there and the optimality criterion and the objective become near zero even though we did not quite reach the goal.

I boiled it down to this example. Create an ultra-simple:
- 1 DoF
- 1 control input
- 1 Control bounds on the input
- Only end-point objectives

You can find the model here:

    %% Dimensions

    nx=2;  % No. of differential states
    nu=1;  % No. of controls
    nz=0;  % No. of algebraic states
    ny=0;  % No. of outputs

    nyN=2; % No. of outputs at the terminal point
    np=0; % No. of model parameters
    nc=0; % No. of general inequality constraints
    ncN=0; % No. of general inequality constraints
    nbx = 0; % No. of bounds on states
    nbu = 1; % No. of bounds on controls

    % state and control bounds-+
    nbx_idx = [];  % indexs of states which are bounded
    nbu_idx = 1;  % indexs of controls which are bounded

    %% create variables

    import casadi.*

    states   = SX.sym('states',nx,1);   % differential states
    controls = SX.sym('controls',nu,1); % control input
    alg      = SX.sym('alg',nz,1);      % algebraic states
    params   = SX.sym('paras',np,1);    % parameters
    refs     = SX.sym('refs',ny,1);     % references of the first N stages
    refN     = SX.sym('refs',nyN,1);    % reference of the last stage
    Q        = SX.sym('Q',ny,1);        % weighting matrix of the first N stages
    QN       = SX.sym('QN',nyN,1);      % weighting matrix of the last stage
    aux      = SX.sym('aux',ny,1);      % auxilary variable
    auxN     = SX.sym('auxN',nyN,1);    % auxilary variable

    %% Dynamics

    %Constant
    mVal = 2;

    p=states(1); 
    pdot = states(2); 

    u1=controls(1);% f1

    % explicit ODE RHS
    x_dot= [pdot; 
     u1/mVal];

    % algebraic function
    z_fun = [];

    % implicit ODE: impl_f = 0
    xdot = SX.sym('xdot',nx,1);
    impl_f = xdot - x_dot;

    %% Objectives and constraints

    % inner objectives
    h=[];
    hN=[p pdot]';

    % outer objectives
    obji =0;% 0.5*(h-refs)'*diag(Q)*(h-refs);
    objN = 0.5*(hN-refN)'*diag(QN)*(hN-refN);

    obji_GGN =0;% 0.5*(aux-refs)'*(aux-refs);
    objN_GGN = 0.5*(auxN-refN)'*(auxN-refN);

    % general inequality path constraints
    general_con = [];
    general_con_N = []; 

    %% NMPC discretizing time length [s]

    Ts_st = 0.01; % shooting interval time

In the file initData.m, I set my initial values as follows:

            x_ini = zeros(nx,1);
            input.x0=x_ini;
            input.u0=zeros(nu,1);
            input.z0 = zeros(nz,1);
            para0 = 0;
            q =0;
            qN = [1, 1];     % pz pzdot
            Q = 0;
            QN = qN';
            % upper and lower bounds for states (=nbx) 
            lb_x = [];
            ub_x = [];
            % upper and lower bounds for controls (=nbu)           
            lb_u = -1;
            ub_u = 1;
            % upper and lower bounds for general constraints (=nc)
            lb_g = [];
            ub_g = [];
            lb_gN = [];
            ub_gN = [];

And my reference trajectory as:

            refss=zeros(1,nx+nu);
            refss(1)=0.1;
            data.REF=refss;

This is the resulting behaviour (plotting the 1 DoF which should reach 0.1):

![Screenshot from 2020-07-29 11-21-05](https://user-images.githubusercontent.com/15928736/88782270-acec9080-d18d-11ea-9669-195a15754b85.png)

And this is the control output. Its is visibly within range:

![Screenshot from 2020-07-29 11-21-22](https://user-images.githubusercontent.com/15928736/88782346-c392e780-d18d-11ea-9c9c-2797d887b037.png)

I tried for several values and I get this behaviour. If I remove all bounds on the control or increase it a lot (ex., 100), I get the expected convergence. But I expect to get the desired convergence within feasible control bounds too. Any explanations or am I doing something wrong?

Thank you

**Comment by gsilano** [comment]
+1

**Comment by chenyutao36** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello,
        Could you please provide the mpc configuration you were using? For example, the number of points in the prediction window, the integrator, the qp solver?I will try to reproduce your example and get back to you soon.Best regards,Yutao
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                chenyutao890704
                            
                    
                        
                            
                                    chenyutao890704@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 7/29/2020 17:28，FirasAbiFarraj<notifications@github.com> wrote： 



Hello,
Thank you for the very nice work. This is a great toolbox with a lot of potential.
I have been playing around with the toolbox and while your examples work and some of my models also worked well, I noticed some issues which I could not explain. Basically, in some scenarios, the system does not manage to achieve the target value of the DoF even if it could. It gets close but not quite there and the optimality criterion and the objective become near zero even though we did not quite reach the goal.
I boiled it down to this example. Create an ultra-simple:

1 DoF
1 control input
1 Control bounds on the input
Only end-point objectives

You can find the model here:
%% Dimensions

nx=2;  % No. of differential states
nu=1;  % No. of controls
nz=0;  % No. of algebraic states
ny=0;  % No. of outputs

nyN=2; % No. of outputs at the terminal point
np=0; % No. of model parameters
nc=0; % No. of general inequality constraints
ncN=0; % No. of general inequality constraints
nbx = 0; % No. of bounds on states
nbu = 1; % No. of bounds on controls

% state and control bounds-+
nbx_idx = [];  % indexs of states which are bounded
nbu_idx = 1;  % indexs of controls which are bounded

%% create variables

import casadi.*

states   = SX.sym('states',nx,1);   % differential states
controls = SX.sym('controls',nu,1); % control input
alg      = SX.sym('alg',nz,1);      % algebraic states
params   = SX.sym('paras',np,1);    % parameters
refs     = SX.sym('refs',ny,1);     % references of the first N stages
refN     = SX.sym('refs',nyN,1);    % reference of the last stage
Q        = SX.sym('Q',ny,1);        % weighting matrix of the first N stages
QN       = SX.sym('QN',nyN,1);      % weighting matrix of the last stage
aux      = SX.sym('aux',ny,1);      % auxilary variable
auxN     = SX.sym('auxN',nyN,1);    % auxilary variable


%% Dynamics

%Constant
mVal = 2;

p=states(1); 
pdot = states(2); 

u1=controls(1);% f1

% explicit ODE RHS
x_dot= [pdot; 
 u1/mVal];

% algebraic function
z_fun = [];

% implicit ODE: impl_f = 0
xdot = SX.sym('xdot',nx,1);
impl_f = xdot - x_dot;

%% Objectives and constraints


% inner objectives
h=[];
hN=[p pdot]';


% outer objectives
obji =0;% 0.5*(h-refs)'*diag(Q)*(h-refs);
objN = 0.5*(hN-refN)'*diag(QN)*(hN-refN);

obji_GGN =0;% 0.5*(aux-refs)'*(aux-refs);
objN_GGN = 0.5*(auxN-refN)'*(auxN-refN);

% general inequality path constraints
general_con = [];
general_con_N = []; 

%% NMPC discretizing time length [s]

Ts_st = 0.01; % shooting interval time

In the file initData.m, I set my initial values as follows:
        x_ini = zeros(nx,1);
        input.x0=x_ini;
        input.u0=zeros(nu,1);
        input.z0 = zeros(nz,1);
        para0 = 0;
        q =0;
        qN = [1, 1];     % pz pzdot
        Q = 0;
        QN = qN';
        % upper and lower bounds for states (=nbx) 
        lb_x = [];
        ub_x = [];
        % upper and lower bounds for controls (=nbu)           
        lb_u = -1;
        ub_u = 1;
        % upper and lower bounds for general constraints (=nc)
        lb_g = [];
        ub_g = [];
        lb_gN = [];
        ub_gN = [];

And my reference trajectory as:
        refss=zeros(1,nx+nu);
        refss(1)=0.1;
        data.REF=refss;

This is the resulting behaviour (plotting the 1 DoF which should reach 0.1):

And this is the control output. Its is visibly within range:

I tried for several values and I get this behaviour. If I remove all bounds on the control or increase it a lot (ex., 100), I get the expected convergence. But I expect to get the desired convergence within feasible control bounds too. Any explanations?
Thank you

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fifarraj** [comment]
Sure. here it is:

    %% solver configurations

    N  = 80;             % No. of shooting points
    settings.N = N;

    N2 = N/5;
    settings.N2 = N2;    % No. of horizon length after partial condensing (N2=1 means full condensing)

    r = 10;
    settings.r = r;      % No. of input blocks (go to InitMemory.m, line 418 to configure)

    opt.hessian         = 'Gauss_Newton';  % 'Gauss_Newton', 'Generalized_Gauss_Newton'
    opt.integrator      = 'ERK4'; % 'ERK4','IRK3','IRK3-DAE'
    opt.condensing      = 'default_full';  %'default_full','no','blasfeo_full(require blasfeo installed)','partial_condensing'
    opt.qpsolver        = 'qpoases'; 
    opt.hotstart        = 'no'; %'yes','no' (only for qpoases, use 'no' for nonlinear systems)

    opt.shifting        = 'no'; % 'yes','no'
    opt.ref_type        = 0; % 0-time invariant, 1-time varying(no preview), 2-time varying (preview)
    opt.nonuniform_grid = 0; % if use non-uniform grid discretization (go to InitMemory.m, line 436 to configure)
    opt.RTI             = 'yes'; % if use Real-time Iteration
 
    %% Initialize Data (all users have to do this)
    if opt.nonuniform_grid
        [input, data] = InitData_ngrid(settings);
        N = r;
        settings.N = N;
    else
        [input, data] = InitData(settings);
    end  

    %% Initialize Solvers (only for advanced users)

    mem = InitMemory(settings, opt, input);

    %% Simulation (start your simulation...)

    mem.iter = 1; time = 0.0;
    Tf = 5;  % simulation time
    state_sim= input.x0';
    controls_MPC = input.u0';
    y_sim = [];
    constraints = [];
    CPT = [];
    ref_traj = [];
    KKT = [];
    OBJ=[];
    numIT=[];

**Comment by chenyutao36** [comment]
Hello,

After some trials, I would say the undesired result you get is because of the objective function. Since you do not have any running cost but only terminal one, the MPC is free to drive the state within the entire the prediction window and applies a big enough control to drive the state to approach the reference at the terminal point. 

To solve this problem, I have added a cost on "u1" with a very small weight (1e-4). This is typical in MPC to avoid such issues. As you can see, the result is very good.

![fig1](https://user-images.githubusercontent.com/10599537/88814055-359a1980-d1ec-11ea-91e1-7b1006f0ff9d.jpg)

**Comment by fifarraj** [comment]
Hmmmm I am trying to reproduce your results but I can't. You added a cost on "u1" throughout the prediction window no?
That is:

    ny=1;
    h=[u1];
    obji = 0.5*(h-refs)'*diag(Q)*(h-refs);
    obji_GGN = 0.5*(aux-refs)'*(aux-refs);

And obviously q =1e-4; and Q = repmat(q',1,N); in initdata??

I got this:

![Screenshot from 2020-07-29 17-32-28](https://user-images.githubusercontent.com/15928736/88820369-87797a00-d1c1-11ea-8690-7d4a6ef949ca.png)
![Screenshot from 2020-07-29 17-32-44](https://user-images.githubusercontent.com/15928736/88820378-8a746a80-d1c1-11ea-9526-3b18b3777bfc.png)

**Comment by chenyutao36** [comment]
The problem is I have states defined in the cost function, even though their weights are zero. I think the difference is due to the automatic differentiation when computing the derivatives of h w.r.t states and controls. I used the following settings.

`ny=3; 
h=[p pdot u1]';
q =[0 0 1e-4];
refss=zeros(1,ny);`

**Comment by fifarraj** [comment]
Indeed this works perfectly well. Thank you very much @chenyutao36 !

**Comment by shuangsw** [comment]
Thank you for your kind sharing. I have tried this code for a fully-actuated multirotor system (modeled as an Euler Lagrange equation).  The model and the target should be OK, since I have successfully controlled it using sliding mode control method. The constraints added are only normal boundary conditions. However it finally gets far away from the target. The objective keeps increasing during the whole process and finally goes to very large. I am confused. Do you have any idea about this issue?
