### ISSUE TITLE
Paths in compile_hpipm.m

### ISSUE THREAD

**Issue by mariobxh** [chenyutao36/MATMPC#3]
Hi,

when following the installation instructions for Windows, the mex_core/compile_hpipm.m script does not run successfully. Turns out that the paths defined in that file do not point to the 'C:\msys64' folder anymore. This change has been introduced with the most recent commit (`6291f59`) and I assume that it was not intended this way.

Kind regards & thanks for this awesome tool!
Mario

**Comment by chenyutao36** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you Mario for pointing this out. I will push a change in the coming days. 
        Best regards,Yutao
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                chenyutao890704
                            
                    
                        
                            
                                    chenyutao890704@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 10/23/2020 03:13，mariobxh<notifications@github.com> wrote： 



Hi,
when following the installation instructions for Windows, the mex_core/compile_hpipm.m script does not run successfully. Turns out that the paths defined in that file do not point to the 'C:\msys64' folder anymore. This change has been introduced with the most recent commit (6291f59) and I assume that it was not intended this way.
Kind regards & thanks for this awesome tool!
Mario

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
