### ISSUE TITLE
The objective keeps increasing during the whole process.

### ISSUE THREAD

**Issue by shuangsw** [chenyutao36/MATMPC#7]
Thank you for your kind sharing. I have tried this code for a fully-actuated multirotor system (modeled as an Euler Lagrange equation). The model and the target should be OK, since I have successfully controlled it using sliding mode control method. The constraints added are only normal boundary conditions. However it finally gets far away from the target. The objective keeps increasing during the whole process and finally goes to very large. I am confused. Do you have any idea about this issue?

**Comment by chenyutao36** [comment]
Hi shuangsw,

From your brief description I cannot figure out what happened. Since MATMPC has been successfully used in many different applications, it is very likely that you made some mistakes when coding. I encourage you to carefully check your code, and if you still cannot obtain the expected results, feel free to send me a minimum example to reproduce your problem.

Best regards,

Yutao
